### ISSUE TITLE
Problem with elements size.

### ISSUE THREAD

**Issue by nikitabelosludtcev** [grapefrukt/grapefrukt-export#13]
Hello, I use the lattest version of grapefrukt-export.

I have made animation character in Adobe Flash.
![enemy fla_1](https://f.cloud.github.com/assets/1511214/1048795/f4555f0a-1093-11e3-9a34-8b741b042eaa.png)

Then, I added  grapefrukt-export and exported character (with script).
![enemy fla_2](https://f.cloud.github.com/assets/1511214/1048813/302eb4cc-1094-11e3-8474-30002757d960.png)

But, there is the troubles with texture size in exported files. I take head to show you example, but there is the same situation with other parts of enemy character.
![enemy fla_3](https://f.cloud.github.com/assets/1511214/1048827/5c966f5a-1094-11e3-8f5f-c0f2a599801b.png)

Can you help me? What's the problem?

**Comment by grapefrukt** [comment]
This is a tricky problem, since there's multiple ways of looking at what the "default" scaling should be. Either, it's they way you're looking at it which is that the first frame decides the size of the generated texture. The second option is to use the 100% scaling of the display object itself, which is the way I designed it. 

So, I'd guess there's a scaling taking place somewhere in the chain, like the container itself being scaled down or something similar. It _may_ also be a bug, but it's hard to say for sure without access to the assets you're using.

A quick fix would be to use the global scaling setting by tweaking the value of `com.grapefrukt.exporter.settings.Settings.scaleFactor` to something like `1.08` before running the export.
