### ISSUE TITLE
How are you keeping things smooth?

### ISSUE THREAD

**Issue by rcurtis** [grapefrukt/grapefrukt-export#15]
Im integrating your animation player into a SFML based engine and all the scaling looks super pixelated during rendering.  Any idea how to smooth those out?

![pixels](https://cloud.githubusercontent.com/assets/1637426/4960922/d402af6e-66c8-11e4-90de-ef34d2f303a4.png)

**Comment by rcurtis** [comment]
Texture smoothing seems to help with some anti-aliasing, but now the drop shadow effects look weird.  Not sure.
![pixel2](https://cloud.githubusercontent.com/assets/1637426/4960983/75432890-66c9-11e4-8223-9852e16b6ae9.png)

**Comment by grapefrukt** [comment]
The first image does indeed seem to be without interpolation, so that'll look a little bit jaggy. I'm not sure what you've enabled in the second one, but those edge artifacts are a telltale sign of issues with premultiplied alpha, which would come out much more with interpolation enabled. 

Either way, this isn't really something the exporter can change, it's all on your rendering end. So, I'm going to close this issue.

**Comment by rcurtis** [comment]
Hey thanks for the response.  I agree this has nothing to do with your exporter, but I would like to ask for a bit more advice trouble shooting this if you don't mind.  What would be the appropriate avenue?

Thanks,
Rob
