### ISSUE TITLE
Export to xml x and y coordinates of the display object

### ISSUE THREAD

**Issue by painkkiller** [grapefrukt/grapefrukt-export#16]
May be I didn't found something, grapefrukt seems very sophisticated project with lots of features, but I have a problem of exporting flash project into Starling. Grapefrukt works well, but I am getting xml which looks like this:

``` xml
<Textures>
  <TextureSheet name="copy1">
    <Texture name="R_05" width="30" height="30" path="copy1/R_05.png" registrationPointX="15.00" registrationPointY="15.00" zIndex="201"/>
...
 <Texture name="n_1_99" width="45" height="40" path="copy1/n_1_99.png" registrationPointX="2.00" registrationPointY="2.00" zIndex="1"/>
  </TextureSheet>
</Textures>
```

There is no coordinates of objects and that's strange why do you need zIndex, if you don't have coordinates? May be I've missed something, or please give me idea how to make it. Thanks in advance!

**Comment by grapefrukt** [comment]
I can see how this might be a little bit confusing. Transformation data (position, scaling, rotation) is considered "animation" and is exported in a separate file, you can take a look at the examples to see how. Due to the way the exporter and Flash works, the zIndex cannot change during an animation, so it's encoded here to save on redundancy in the animation files. 
Using the atlas exporter will give you x/y values, but that will be for the position in the atlas, not their position "on the screen".

**Comment by painkkiller** [comment]
Never mind I already did it on my own. Just parsed display list of my swf and added x and y values to XML. Looks perfect. Thanks for excellent project and quick responce!

**Comment by grapefrukt** [comment]
If you're happy, I'm happy!
