### ISSUE TITLE
Flash project file?

### ISSUE THREAD

**Issue by rroc** [grapefrukt/grapefrukt-export#2]
Hi, 
the exporter seems very nice! Perhaps you could add the flp- project file to help trying to mess around with the project. I was planning to try out exporting to a custom format, and thus would need to create a custom exporter .swc. Or what do you think is the best way to start modifying/adding stuff to the exporter?

**Comment by grapefrukt** [comment]
I haven't added project files because with all the different IDE's people are using they would clog up the project. I personally mostly use FlashDevelop, then there's Flash Builder, Flash Authoring, FDT, and IntelliJ, not to mention all other custom setups. 

You don't really need to make a .swc to mess around with the project, instead, in flash authoring add the src folder as a source folder and the lib-swc folder as a swc-folder. Then you can edit and extend the source using your preferred editor and easily try to export.

**Comment by rroc** [comment]
Thanks for the reply! I am relatively new to ActionScript developing(only have done script development inside the Flash before) so that is why any project file would have helped. :) 

I created an empty project in the grapefrukt extractor folder in FlashDevelop, and hit the "Build Project"... unfortunately it does not compile. The mtasc.exe would need some files as input... If I set for example the SimpleExport.as as 'Always Compile' I only get:

SimpleExport.as:29: characters 0-7 : parse error Unexpected package
Build halted with errors (mtasc).

It seems that the error might be related to the FlashDevelop trying to compile the project as AS2 when it should use the AS3, but I could not find such setting in the project. ...again a working project file might have been nice :)

**Comment by grapefrukt** [comment]
You'll for sure need to do an actionscript project, but really, there's not much use to compile the lib with flashdevelop (unless you're building the swc, which you don't need). You can set up flash authoring to compile instead and just use flashdevelop to code with, that's what I do when I'm working on this.

**Comment by rroc** [comment]
thanks!

for the reference:
Flash/Edit/Preferences/ActionScript/Language:ActionScript 3.0 Advanced Settings
Add source and library paths (to grapefrukt src and lib-swc)
