### ISSUE TITLE
Shared zIndex

### ISSUE THREAD

**Issue by boxofrobots** [grapefrukt/grapefrukt-export#4]
Hi, we're using the exporter and it's awesome, thanks.

One thing we run into, is that sometimes zIndex isn't correct.  

There are a bunch of layers in the exported sheet that share a zIndex, can you describe where zIndex is coming from?  We do a bunch of things such as duplicate art and give it different symbol names, so I'm wondering if this has something to do with it.  Our solution right now is to manually change the zIndex for the texture's that are out of order.   

Thanks!
-David

**Comment by grapefrukt** [comment]
Layers are removed at compile time so there's no way for the exporter to see the order they were created in. 
This means zIndex has to be inferred from the order of the items as they are discovered. This is a bit of a hack, but there's no elegant way to solve it (as far as I've looked into it atleast). 

Your problem arises when all objects are not present at the first frame, then I have to guess the order as the object is encountered later in the animation and all I have to compare with are the other present objects. 

A quick solution to the problem is to have all items present in the animation on the first frame. This will let the exporter figure out the order easily. 

If you have a set preference for zIndex ordering you could open the [zIndex](https://github.com/grapefrukt/grapefrukt-export/blob/master/src/com/grapefrukt/exporter/textures/TextureBase.as#L50) property for writing with a setter and add some code to manually set the zIndex to your liking. 

The actual inferrence of zIndex happens in the [TextureExtractor](https://github.com/grapefrukt/grapefrukt-export/blob/master/src/com/grapefrukt/exporter/extractors/TextureExtractor.as#L170).

**Comment by sanxfxteam** [comment]
I did a quick hack to export the zindex by frame and use it for animation, solves most of our use cases.
https://github.com/sanxfxteam/grapefrukt-export/commit/d9aecbdfff25fa9aa022442e9509a8918c21e5ea

**Comment by cottrelld** [comment]
Sounds promising! 

We've been making a burner frame as the first frame of every file and making sure that it contains everything, as well as having no object ever be reused on another layer.  It blows up the number of layers but for the most part has been working for us.

How does your change work?  I looked and the latest binary seems to be from a month ago?
-David

**Comment by sanxfxteam** [comment]
We used to do like you do, but it's a lot of maintenance, this system
avoids the problem.
It's not a clean integration because we've branched away from the original
exporter a long time ago.
I don't have up-to-date binaries.

I wanted to share the change to inspire you to do a clean change, because
it's not a lot of work, one more index parameter and a sort after the
animations are created.

Laurent,

**Comment by sanxfxteam** [comment]
I just realized it does not work in its current state, I'll fix it and I'll
post again. Sorry about that.

**Comment by sanxfxteam** [comment]
Back to the old way of getting the max z-index. It's still not the real zindex, because the zindex changes every frame depending on which clips are visible or hidden.
https://github.com/sanxfxteam/grapefrukt-export/commit/c4b9dedb81b8f74822dc9f3bf1e75910c70861cf

**Comment by grapefrukt** [comment]
Okay, since there's obviously some demand for this being fixed I'll look into doing a better job of suppling the zIndex. I can't really merge the changes from @sanxfxteam since it doesn't match the style or as far as I can tell will apply cleanly. But, I'll try to whip up some new code that should work better than the current implementation.

**Comment by grapefrukt** [comment]
Okay, just pushed [a set of changes](https://github.com/grapefrukt/grapefrukt-export/commit/81a8d135d55d5b92bcb41aafe5e3639cdf482ae6) that should resolve this issue, I didn't have any suitable material handy to really test this as thoroughly as might be needed, but I'm sure it's at the very least better than the previous implementation.

The way it works now is that it loops over the list of children (starting from the lowest zIndex), and if any share a zIndex, the following children are moved "up" one step. This means that the order of objects that share a zIndex might get swapped, but, the reason they share a zIndex in the first place is that they're not present on the same frame. 

Could you guys try this and report back if it works for you? The first "burner" frame should not be needed anymore.

**Comment by grapefrukt** [comment]
Nothing has happened here for months, so I'm going to assume this resolved your issue.
