### ISSUE TITLE
Could you please add feature to export alpha and flip for key frame?

### ISSUE THREAD

**Issue by vhson13** [grapefrukt/grapefrukt-export#9]
I tried to use flash to create character's animations with some parts need flip and alpha. But when I export animation to xml and sheet, I noticed that there no alpha or flip property. Could you add these properties for animation's frame?

**Comment by grapefrukt** [comment]
Alpha values are exported when they are != 1, this is to make the xml file smaller, it also applies to scaling, positioning and other values. 

I'm unsure what you mean with "flip", but I assume you mean something like Modify -> Transform -> Flip Horizontal or setting the horizontal scaling to -100%. To get a perfect export of this you will need to use the [Matrix export](https://github.com/grapefrukt/grapefrukt-export/blob/master/src/com/grapefrukt/exporter/serializers/data/XMLDataWithMatrixSerializer.as), since Flash (most of the time, but not always) insists on moving this transformation to be a skew instead of a negative scaling. 
If you _do_ figure out how to keep it being a negative scaling, it will be exported even using the "regular" export.

**Comment by vhson13** [comment]
Thanks for your responding. I can use alpha now. I'll try with skew instead of Flip Horizontal.
